version: '3.9'

services:
  reverse-proxy:
    image: traefik:v2.5
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./traefik.yaml:/etc/traefik/traefik.yaml:ro"
    ports:
      - 80:80
      - 443:443
      - 8080:8080

  pgadmin:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.horizon-efrei.fr`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=5050"
    # expose:
    #   - 5050

  typesense:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.typesense.rule=Host(`typesense.horizon-efrei.fr`)"
      - "traefik.http.routers.typesense.entrypoints=websecure"
      - "traefik.http.routers.typesense.tls=true"

  api:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.horizon-efrei.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.services.api.loadbalancer.server.port=8081"
